### ISSUE TITLE
Variable Sized Arrays

### ISSUE THREAD

**Issue by astha2412** [arpit456jain/DSA-Path-And-Important-Questions#9]
Consider an n-element array, a, where each index i in the array contains a reference to an array of k[i] integers (where the value of k[i] varies from array to array).

Given a, you must answer q queries. Each query is in the format i, j, where i denotes an index in array a and k denotes an index in the array located at a[i]. For each query, find and print the value of element j in the array at location a[i] on a new line.

**Comment by arpit456jain** [comment]
@astha2412 please write the question name in issue title and describe about it a little bit in description

**Comment by astha2412** [comment]
> @astha2412 please write the question name in issue title and describe about it a little bit in description

> ok @arpit456jain

**Comment by arpit456jain** [comment]
mention the language also
